import { Azeret_Mono } from 'next/font/google'
import Header from "./_components/Header"
import Wrapper from "./_components/Wrapper";
import "./globals.css"

const azeret = Azeret_Mono({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'LA ESCUELA DEL FOGÓN',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es" className={`
      ${azeret.className} bg-neutral-50`}>
      <body>
        <Header />
        <Wrapper>
          {children}
        </Wrapper>
      </body>
    </html>
  )
}
