import Link from "next/link"
import Nav from "./_components/Nav"


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
        <body>
          <div style={{ backgroundColor: "lightblue", padding: "1rem" }}>
              <Nav/>
          </div>
          {children}
        </body>
    </html>
  )
}
